import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import db from "@/lib/supabase/db";
import connectMongoDB from "@/lib/mongodb";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  connectMongoDB()
  // console.log(db)
  return (
    <html lang="ar">
      <body className={inter.className}>
          {children}
      </body>
    </html>
  );
}
